### ISSUE TITLE
When the *clang-complete* buffer is killed, it is impossible to kill a c/c++ buffer

### ISSUE THREAD

**Issue by To1ne** [Golevka/emacs-clang-complete-async#9]
To test this:
- Kill the `*clang-complete*` buffer
- Try to kill a .c/.cpp buffer.

You will get the following error:

```
Process clang-complete not running
```

So the `kill-buffer-hook` to end the completion for a c/c++ buffer causes trouble.

**Comment by Golevka** [comment]
I tried to fix it in my last commit, you can check if it could work for you.

**Comment by To1ne** [comment]
I have been using [my fork](https://github.com/To1ne/emacs-clang-complete-async) until just now.

With your version I get the following errors:

> ac-clang-send-cmdline-args: Buffer main.cpp has no process
> 
> rename-buffer: Buffer name `main.cpp' is in use

The `clang` process isn't started for any buffer.

I also tried 3e62592e6a469a68573068c3a18029e4353cfa3f , which gave the same errors. Thus the errors above are not related to your latest change.

**Comment by Golevka** [comment]
The emacs configuration code changed a little bit since merging pull request #8, lots of variable/function names has changed to comform elisp's naming convention (such as 'clang-complete-executable' renamed to 'ac-clang-complete-executable'). You can check out the lastest README for a new sample configuration script.

The previous version could not bring up auto-complete when cl is not loaded, but the clang-complete process launched without problem. This fault is taken care in commit be5edfa58cee3cb50390cda2021be868659fa1f7

**Comment by To1ne** [comment]
Thanks for the info, after some changes in my configuration I've tested ccd0a082dc79bf877db6d8d1332aa3694c24cd95. With this version this issue is solved.
